name: Build

on: [push]

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Java-API and Windows-x86_64 native
      run: mvn -B install --file pom.xml
    - name: Archive Java-API artifact
      uses: actions/upload-artifact@v1
      with:
        name: java-api
        path: target/video-capture-inventory-0.1.1.jar
    - name: Archive windows-x86_64 native artifact
      uses: actions/upload-artifact@v1
      with:
        name: windows-x86_64 native
        path: target/video-capture-inventory-0.1.1-windows-x86_64.jar

  build-linux:

    needs: build-windows
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Linux natives
      run: mvn -B install -Pnatives-only --file pom.xml

    - name: Archive linux-x86_64 native artifact
      uses: actions/upload-artifact@v1
      with:
        name: linux-x86_64 native
        path: target/video-capture-inventory-0.1.1-linux-x86_64.jar
    - name: Archive linux-armhf native artifact
      uses: actions/upload-artifact@v1
      with:
        name: linux-armhf native
        path: target/video-capture-inventory-0.1.1-linux-armhf.jar
