name: Build and Deploy

on:
  release:
    types:
    - published

jobs:
  build-windows:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build and Deploy Java-API and Windows-x86_64 native
      run: mvn -B install deploy --file pom.xml
      env:
        GITHUB_TOKEN: ${{ github.token }}

  build-linux:

    needs: build-windows
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build Linux natives
      run: mvn -B install deploy -Pnatives-only --file pom.xml
